# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyfeedcontract/feed.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19pyfeedcontract/feed.proto\x12\x12synoptic.feed.feed\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdd\x01\n\x0b\x46\x65\x65\x64Message\x12\x0f\n\x07\x66\x65\x65\x64_id\x18\x01 \x01(\t\x12\x12\n\nmessage_id\x18\x02 \x01(\t\x12\x10\n\x08headline\x18\x03 \x01(\t\x12\x35\n\x11timestamp_scraper\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x17\n\nconfidence\x18\x05 \x01(\x05H\x00\x88\x01\x01\x12\x11\n\x04\x64\x61ta\x18\x06 \x01(\tH\x01\x88\x01\x01\x12\x12\n\x05_meta\x18\x07 \x01(\tH\x02\x88\x01\x01\x42\r\n\x0b_confidenceB\x07\n\x05_dataB\x08\n\x06X_meta\"$\n\x13SubscriptionRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\x1b\n\x19SubmitFeedMessageResponse2f\n\x0b\x46\x65\x65\x64Service\x12W\n\tSubscribe\x12\'.synoptic.feed.feed.SubscriptionRequest\x1a\x1f.synoptic.feed.feed.FeedMessage0\x01\x32\xdf\x01\n\x0eIngressService\x12\x63\n\x11SubmitFeedMessage\x12\x1f.synoptic.feed.feed.FeedMessage\x1a-.synoptic.feed.feed.SubmitFeedMessageResponse\x12h\n\x12SubmitFeedMessages\x12\x1f.synoptic.feed.feed.FeedMessage\x1a-.synoptic.feed.feed.SubmitFeedMessageResponse(\x01\x30\x01\x42\x33Z1github.com/synoptic-com/opticfeeds/gofeedcontractb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pyfeedcontract.feed_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z1github.com/synoptic-com/opticfeeds/gofeedcontract'
  _globals['_FEEDMESSAGE']._serialized_start=83
  _globals['_FEEDMESSAGE']._serialized_end=304
  _globals['_SUBSCRIPTIONREQUEST']._serialized_start=306
  _globals['_SUBSCRIPTIONREQUEST']._serialized_end=342
  _globals['_SUBMITFEEDMESSAGERESPONSE']._serialized_start=344
  _globals['_SUBMITFEEDMESSAGERESPONSE']._serialized_end=371
  _globals['_FEEDSERVICE']._serialized_start=373
  _globals['_FEEDSERVICE']._serialized_end=475
  _globals['_INGRESSSERVICE']._serialized_start=478
  _globals['_INGRESSSERVICE']._serialized_end=701
# @@protoc_insertion_point(module_scope)
