# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyfeedcontract/feed.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19pyfeedcontract/feed.proto\x12\x12synoptic.feed.feed\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfc\x01\n\x0b\x46\x65\x65\x64Message\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0e\n\x06\x66\x65\x65\x64Id\x18\x02 \x01(\t\x12\x11\n\tmessageId\x18\x03 \x01(\t\x12\x10\n\x08headline\x18\x04 \x01(\t\x12\x35\n\x11timestamp_scraper\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x17\n\nconfidence\x18\x06 \x01(\x05H\x00\x88\x01\x01\x12\x14\n\x07message\x18\x07 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0bmessageMeta\x18\x08 \x01(\tH\x02\x88\x01\x01\x42\r\n\x0b_confidenceB\n\n\x08_messageB\x0e\n\x0c_messageMeta\"$\n\x13SubscriptionRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\x1b\n\x19SubmitFeedMessageResponse2f\n\x0b\x46\x65\x65\x64Service\x12W\n\tSubscribe\x12\'.synoptic.feed.feed.SubscriptionRequest\x1a\x1f.synoptic.feed.feed.FeedMessage0\x01\x32\xdf\x01\n\x0eIngressService\x12\x63\n\x11SubmitFeedMessage\x12\x1f.synoptic.feed.feed.FeedMessage\x1a-.synoptic.feed.feed.SubmitFeedMessageResponse\x12h\n\x12SubmitFeedMessages\x12\x1f.synoptic.feed.feed.FeedMessage\x1a-.synoptic.feed.feed.SubmitFeedMessageResponse(\x01\x30\x01\x42\x33Z1github.com/synoptic-com/opticfeeds/gofeedcontractb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pyfeedcontract.feed_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z1github.com/synoptic-com/opticfeeds/gofeedcontract'
  _globals['_FEEDMESSAGE']._serialized_start=83
  _globals['_FEEDMESSAGE']._serialized_end=335
  _globals['_SUBSCRIPTIONREQUEST']._serialized_start=337
  _globals['_SUBSCRIPTIONREQUEST']._serialized_end=373
  _globals['_SUBMITFEEDMESSAGERESPONSE']._serialized_start=375
  _globals['_SUBMITFEEDMESSAGERESPONSE']._serialized_end=402
  _globals['_FEEDSERVICE']._serialized_start=404
  _globals['_FEEDSERVICE']._serialized_end=506
  _globals['_INGRESSSERVICE']._serialized_start=509
  _globals['_INGRESSSERVICE']._serialized_end=732
# @@protoc_insertion_point(module_scope)
